name: ssecretdiary
description: The mobile presentation layer for secret diary project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  shared_preferences: ^0.5.7
  flutter_svg: ^0.17.4

  # Modules
  common_ui:
    path:
      ../common_ui

  sddomain:
    path:
      ../sd_domain

  sd_data:
    path:
      ../sd_data

  sd_base:
    path:
      ../sd_base

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
