name: ssecretdiary
description: The mobile presentation layer for secret diary project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  shared_preferences: ^0.5.7

  # Modules
  sddomain:
    path:
      ../sd_domain

  sddata:
    path:
      ../sd_data

  sdbase:
    path:
      ../sd_base

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  module:
    androidX: true
    androidPackage: com.nr.ssecretdiary
    iosBundleIdentifier: com.nr.ssecretdiary
