name: sd_data
description: The data layer for secret diary front end project.
version: 0.0.1
author: bohdan.martynov

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.7

  # firebase
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2

  sd_base:
    path:
      ../sd_base

  sddomain:
    path:
      ../sd_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter: