name: sddomain
description: A domain layer for secret diary front end project.
version: 0.0.1
author: bohdan.martynov

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  rxdart: ^0.24.0

  sdbase:
    path:
      ../sd_base

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
