#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/bohdan.martynov/sdk/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/bohdan.martynov/Work/secret-diary/secret-diary-frontend/sdmob_presentation"
export "FLUTTER_TARGET=/Users/bohdan.martynov/Work/secret-diary/secret-diary-frontend/sdmob_presentation/lib/targets/dev/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/bohdan.martynov/sdk/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
